package com.ijoyz.moka.data;

import java.util.Date;
import java.util.List;

import junit.framework.TestCase;

import org.apache.commons.lang.StringUtils;

import com.ijoyz.moka.model.Gang;
import com.ijoyz.moka.model.GangMember;
import com.ijoyz.moka.model.Gangs;
import com.ijoyz.moka.model.League;
import com.ijoyz.moka.model.LeagueData;

/**
 * The class <code>GeneralLeagueDataWriterTest</code> contains tests for the
 * class {@link <code>GeneralLeagueDataWriter</code>}
 * 
 * @pattern JUnit Test Case
 * 
 * @generatedBy CodePro at 13-4-22 �* 4:32
 * 
 * @author zhushijun@corp.netease.com
 * 
 * @version $Revision$
 */
public class GeneralLeagueDataWriterTest extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public GeneralLeagueDataWriterTest(String name) {
		super(name);
	}

	public void testWrite() {
		Gang gang = new Gangs().getGang(1000);
		GangMember member = new GangMember(gang, 226520047, "天神下凡");
		gang.addMember(member);
		League league = gang.newLeague("巅峰王朝", false, new Date());
		String[] split1 = StringUtils.split("__莫、葬爱          145   射手  137   194   0     2259", ' ');
		String[] split2 = StringUtils.split("玩家名称            等级  职业  杀敌  助攻  维修  英雄积分", ' ');
		String[] split3 = StringUtils.split("天神下凡            144   方士  87    282   0     3939", ' ');
		GeneralLeagueDataWriter writer = new GeneralLeagueDataWriter();
		writer.writeTo(split1, league);
		writer.writeTo(split2, league);
		writer.writeTo(split3, league);
		List<LeagueData> data = league.getLeagueData();
		assertEquals(data.size(), 1);
		LeagueData leagueData = data.get(0);
		int assist = leagueData.getAssist();
		int heads = leagueData.getHeads();
		int repair = leagueData.getRepair();
		assertEquals(assist, 282);
		assertEquals(heads, 87);
		assertEquals(0, repair);
	}

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.ijoyz.moka.data
 * package.sourceFolder = iJoyz-Latte/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = GeneralLeagueDataWriterTest
 * testClassType = com.ijoyz.moka.data.GeneralLeagueDataWriter
 */